-- Supabase: buat tabel artikel untuk admin CRUD
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> New query -> Run
-- Setelah tabel dibuat, artikel dibaca/ditulis langsung ke sini dari frontend (lib/supabase.js).

create table if not exists public.artikel (
  id bigint generated by default as identity primary key,
  judul text not null,
  tanggal timestamp,
  isi text,
  gambar text,
  published integer not null default 0,
  views integer not null default 0,
  created_at timestamptz not null default now()
);

-- Aktifkan Row Level Security, lalu izinkan akses penuh role anon (dipakai frontend).
alter table public.artikel enable row level security;

drop policy if exists "artikel_all_anon" on public.artikel;
create policy "artikel_all_anon"
  on public.artikel for all
  to anon
  using (true)
  with check (true);

drop policy if exists "artikel_all_authenticated" on public.artikel;
create policy "artikel_all_authenticated"
  on public.artikel for all
  to authenticated
  using (true)
  with check (true);

-- Index agar pencarian/urut by tanggal cepat
create index if not exists artikel_tanggal_idx on public.artikel (tanggal desc);
